# Generated by Django 3.2.22 on 2023-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_athlete_id', models.CharField(max_length=128, unique=True)),
                ('strava_access_token', models.CharField(max_length=128)),
                ('strava_refresh_token', models.CharField(max_length=128)),
                ('strava_token_expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlackBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_id', models.CharField(max_length=32, null=True)),
                ('enterprise_name', models.TextField(null=True)),
                ('team_id', models.CharField(max_length=32, null=True)),
                ('team_name', models.TextField(null=True)),
                ('bot_token', models.TextField(null=True)),
                ('bot_refresh_token', models.TextField(null=True)),
                ('bot_token_expires_at', models.DateTimeField(null=True)),
                ('bot_id', models.CharField(max_length=32, null=True)),
                ('bot_user_id', models.CharField(max_length=32, null=True)),
                ('bot_scopes', models.TextField(null=True)),
                ('is_enterprise_install', models.BooleanField(null=True)),
                ('installed_at', models.DateTimeField()),
                ('users', models.ManyToManyField(to='stravabot.User')),
            ],
        ),
        migrations.AddIndex(
            model_name='slackbot',
            index=models.Index(fields=['enterprise_id', 'team_id', 'installed_at'], name='stravabot_s_enterpr_285f86_idx'),
        ),
    ]
