# Generated by Django 3.2.22 on 2023-11-03 10:02

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stravabot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackbot',
            name='bot_refresh_token',
            field=django_cryptography.fields.encrypt(models.TextField(null=True)),
        ),
        migrations.AlterField(
            model_name='slackbot',
            name='bot_token',
            field=django_cryptography.fields.encrypt(models.TextField(null=True)),
        ),
        migrations.AlterField(
            model_name='slackbot',
            name='installed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='strava_access_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=128)),
        ),
        migrations.AlterField(
            model_name='user',
            name='strava_refresh_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=128)),
        ),
    ]
