import os

HOST = "http://localhost:3000"

KV_STORE_TABLE = os.environ["KV_STORE_TABLE"]
JWT_SECRET_KEY = os.environ["JWT_SECRET_KEY"]

STRAVA_CLIENT_ID = os.environ["STRAVA_CLIENT_ID"]
STRAVA_CLIENT_SECRET = os.environ["STRAVA_CLIENT_SECRET"]
STRAVA_WEBHOOK_VERIFY_TOKEN = os.environ["STRAVA_WEBHOOK_VERIFY_TOKEN"]
STRAVA_EVENT_HANDLER = os.environ.get("STRAVA_EVENT_HANDLER", "")
