KV_STORE_TABLE = "KV_STORE_TABLE"
JWT_SECRET_KEY = "secret"

STRAVA_CLIENT_ID = "12345"
STRAVA_CLIENT_SECRET = "678910"
STRAVA_WEBHOOK_VERIFY_TOKEN = "token"
STRAVA_EVENT_QUEUE_URL = "event-queue-url"
STRAVA_CALLBACK_URL = "https://strava-callback-url/here"
