name: Build and deploy

on:
  - push
  - pull_request

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r lambda/requirements.txt
          pip install boto3
      - name: lint
        run: |
          make lint
      - name: typing
        run: |
          make mypy
      - name: unit tests
        run: |
          make unit
