name: CDK Diff

on: 
  push:
    branches:
      - main

  workflow_run:
    workflows:
      - Run Tests
    types:
      - completed

jobs:
  diff:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Hello
        run: |
          echo "Hello"
